### PR TITLE
resource example added

### PR DESCRIPTION
**Pull request by kunjee17**

### CODE REVIEW

**Comment by kunjee17** [comment]
@alfonsogarciacaro I have added the example. It is not working though but I did try to mimic solid js example. Can you please help me with this ? Means what I am missing or what can be update in Solid wrapper to support near api to Solid js.

**Comment by alfonsogarciacaro** [comment]
Thanks @kunjee17! You made me realize there was a type error in the API, I fixed that.

I've made a couple of changes to the sample, but I think besides the issue mentioned above the sample didn't work for you because of two reasons:

- In F# interfaces are not callable so I had to use `.current` for the value, so we need to access the value by typing `user.current` instead of `user()`
- Solid doesn't accept conditionals for JSX elements, you need to use `Show`. Unfortunately, Solid doesn't give a proper error message for this situation.

```
// Example, following line works
Html.span (if foo() then "foo" else "")

// This doesn't work
if foo() then Html.span "foo" else Html.None
```

**Comment by kunjee17** [comment]
@alfonsogarciacaro I always forget Solid is without vdom. And it will not re-render just like that. Coming from react that one thing always caught me off guard. Thanks for pointing it out.

**Comment by alfonsogarciacaro** [comment]
Sorry @kunjee17, I just realized I forgot to push the commit 😅 These are the fixes: c38942452488e8241927b5881897112aff9173b9

BTW, I couldn't make `user.error` or `user.state` work, not sure why.

**Comment by alfonsogarciacaro** [comment]
@kunjee17 Actually I was wrong, Solid supports conditional expression for elements. The problem here is F#/Fable was generating a List builder and this is not compatible with Solid (React supports any iterable for children, but Solid seems to be compatible only with arrays). I need to fix a few things and maybe your original example can be supported, although `Show` seems to still be preferred by Solid for performance (I also had some issues with the input focus when using a list builder).

**Comment by kunjee17** [comment]
@alfonsogarciacaro Oh great. Yes there are some underlying differences between solid and react. In regard of `show` I just copy pasted ( kind of one to one converted ) example given in Solid js official tutorial.  I totally agree that show would be better option. I did get bitten on re-rendering issue when I didn't use show in Solidjs typescript example I was trying so yes agreed.

**Comment by alfonsogarciacaro** [comment]
One issue here is that things have become a bit ambiguous since F# allowed removing `yield`. So in your original example it's compiled as a list builder, which causes problems, but if you surround the conditional with parenthesis it's compiled as a list literal and it actually works!

```fsharp
        Html.fragment [
            Html.label $"UserID : {userId()}"
            Html.br []
            Html.input [
                Attr.typeNumber
                Attr.min 1
                Attr.placeholder "Enter Numeric Id"
                Ev.onTextInput (fun (value: string) -> value |> Some |> setUserId)
            ]
            (if user.loading then Html.span "Loading" else Html.none)
            Html.div [
                Html.pre $"{JSON.stringify(user())}"
            ]
        ]
```

Another option is to use JSX, in that case there's no ambiguity and it works too:

```fsharp
        JSX.html $"""
        <>
            <p>User ID: {userId() |> Option.defaultValue ""} {if user.loading then " (Loading...)" else ""}</p>
            <input
                type="number"
                min="1"
                placeholder="Enter numeric ID"
                onchange={fun (ev: Event) -> ev.target?value |> Some |> setUserId}>
            </input>
            {if user.loading then Html.p "Loading" else Html.none}
            <ul>
            {
                Solid.For(keyValues user.current, fun (k, v) _ ->
                    Html.li [
                        Html.children [
                            Html.strong k
                            Html.text $": {string v}"
                        ]
                    ]
                )
            }
            </ul>
        </>
        """
```

**Pull request merged**
