### PR TITLE
Solid1.8

### PR DESCRIPTION
**Pull request by goswinr**
This is a replacement for https://github.com/fable-compiler/Fable.Solid/pull/17 . It has no formatting changes. And is broken down into several commits. Can I merge @MangelMaxime ?

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Looks good to me.

Could you please give me here or on Slack your NuGet handle so I can add you to the owner list on NuGet. This is to allow you to push new releases

**Comment by goswinr** [comment]
https://www.nuget.org/profiles/goswinr

**Comment by goswinr** [comment]
Can I make a GitHub pages on this repo to host the sample app? Or should it go somewhere else?

**Comment by MangelMaxime** [comment]
Sure you can create one. 

In general, we deploy from a branch called `gh-pages` . [This NPM tool](https://www.npmjs.com/package/gh-pages) is handy for doing the deployment/push work

**Comment by goswinr** [comment]
@MangelMaxime its up at https://fable.io/Fable.Solid/ . I will pulish nuget next, shall i use this script https://github.com/fable-compiler/Fable.Solid/blob/master/build.fsx with [Fable.PublishUtils](https://www.nuget.org/packages/Fable.PublishUtils) ?

**Comment by MangelMaxime** [comment]
@goswinr Yes it should works.

The first time, it will probably fails because it will not find the Nuget API Key in your system env. But just run it, it will tells you the name of env variable to store the key.

If you want something more fancy automated, I encourage you to look for Glutinum.Template which should be released in the coming days.

More fancy meaning:

- Automatic version calculation
- Generate changelog based on Git history
- etc.
- and a simpler life as a maintainer 🤣

**Pull request merged**
